language: node_js
node_js:
  - "16"
install:
  - npm install
script:
  - npm run cover:check
# Node 6 doesn't run prepare after install:
before_script: "npm run build"
# Send test coverage data to Coveralls:
after_script: "npm run coveralls"
